apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tomcat-hello
spec: 
  selector:
    matchLabels:
      app: k8s-tomcat-hello
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-tomcat-hello
    spec: 
      containers:
      - name: k8s-tomcat-hello
        image: registry.cn-shenzhen.aliyuncs.com/zulin/k8s-tomcat-hello
        ports: 
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-tomcat-hello-svc
  labels:
    app: k8s-tomcat-hello
spec: 
  ports: 
    port: 80
    targetPort: 8080
  selector:
    app: k8s-tomcat-hello