apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tomcat-hello-call
spec: 
  selector:
    matchLabels:
      app: k8s-tomcat-hello-call
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-tomcat-hello-call
    spec: 
      containers:
      - name: k8s-tomcat-hello-call
        image: registry.cn-shenzhen.aliyuncs.com/zulin/k8s-tomcat-hello-call

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-tomcat-hello-call-svc
  labels:
    app: k8s-tomcat-hello-call
spec: 
  type: NodePort
  ports: 
    port: 80
    targetPort: 8080
  selector:
    app: k8s-tomcat-hello-call